# Generated by Django 5.2.11 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("donor", "Donor"),
                    ("ngo", "NGO"),
                    ("volunteer", "Volunteer"),
                ],
                default="donor",
                max_length=20,
            ),
        ),
    ]

