# Generated by Django 5.2.11 on 2026-02-28 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ngos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ngoprofile",
            options={"ordering": ("-verified", "name")},
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1400&q=80",
            ),
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1469571486292-b53601020d26?auto=format&fit=crop&w=400&q=80",
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]

