# Generated by Django 5.2.11 on 2026-02-28 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="campaign",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1400&q=80",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="location",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="category",
            field=models.CharField(blank=True, default="General", max_length=100),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="goal_amount",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="raised_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]

